import React, { useEffect, useState, useRef, useCallback } from 'react';
import { 
  BookOpen, 
  HelpCircle, 
  Leaf, 
  Clock, 
  Calendar, 
  ArrowRight, 
  X, 
  Home, 
  Car, 
  Utensils, 
  ShoppingBag, 
  ShieldCheck, 
  Flame, 
  Anchor, 
  Trees 
} from 'lucide-react';
import './Resources.css';

interface ResourcesProps {
  initialSection: 'methodology' | 'blog' | 'offset' | null;
  onClearSection?: () => void;
}

interface Article {
  id: string;
  title: string;
  tag: string;
  readTime: string;
  date: string;
  summary: string;
  image: string;
  content: React.ReactNode;
}

export const Resources: React.FC<ResourcesProps> = ({ initialSection, onClearSection }) => {
  const [activeTab, setActiveTab] = useState<'methodology' | 'blog' | 'offset'>('methodology');
  const [selectedArticle, setSelectedArticle] = useState<Article | null>(null);

  const methodologyRef = useRef<HTMLDivElement>(null);
  const blogRef = useRef<HTMLDivElement>(null);
  const offsetRef = useRef<HTMLDivElement>(null);

  // Articles Database
  const articles: Article[] = [
    {
      id: 'digital-spending',
      title: 'The Digital Phantom: Hidden Impacts of Fast Fashion & E-Commerce',
      tag: 'Lifestyle',
      readTime: '6 min read',
      date: 'June 18, 2026',
      summary: 'Explore how quick delivery clicks and online shopping sprees translate into heavy global supply chain and packaging emissions.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7eGblkkJTkXXdcTcd63Y6ActtaFNyBgFMBZq2GWB2Ar5Lg0jzdx8sl62n5M2RXelUaR5gU5c4JAbd3Ro75Sld1erBEOl4JUQsbaHJeEFSsvsG5HPy288CFnr91rmq9pnG7YuP3YmKdpz2ulL3bfRnGPz4MYur52PfWy9kXoFalosotqOjMFcsPlwojy7jstllYVXn398_klfgOKyKBst1StnWQSj-Ex3SzgWCai4LyQckLNDRlOaEI8AvJFAKwaeMTgpvYr60bqdm',
      content: (
        <div className="blog-modal-text">
          <p>Every time we click "Buy Now" on our screens, we trigger an unseen chain reaction across warehouses, ocean freighters, cargo planes, and final-mile delivery vans. Fast fashion and the rise of next-day delivery have dramatically increased carbon footprints under the "Lifestyle & Waste" category.</p>
          <h3>The Lifecycle of a Modern Purchase</h3>
          <p>From resource extraction (like synthetic polyester derived from petroleum) to chemical dyeing, assembly, international shipping, and packaging, a single pair of jeans can release up to 33.4 kg of CO₂. That is equivalent to driving over 130 kilometers in a standard petrol car!</p>
          <p>Online retailing also creates a massive waste problem. E-commerce packaging produces millions of tons of plastic and paper board wrap yearly. Furthermore, because return logistics are complex, up to 30% of returned clothing items are sent directly to landfills or incinerators instead of being re-sold.</p>
          <h3>How to Transition to Sustainable Consumption</h3>
          <ul>
            <li><strong>Adopt a Minimalist Mindset:</strong> Question if a purchase is an essential need or a temporary want. Buying fewer items is the single most effective reduction strategy.</li>
            <li><strong>Prioritize Second-Hand & Thrifting:</strong> Purchasing circular fashion saves up to 80% of the emissions generated by manufacturing new garments.</li>
            <li><strong>Select Consolidated Shipping:</strong> Opting for standard slow shipping rather than "one-day express" allows delivery fleets to pack trucks efficiently, cutting down total mileage.</li>
            <li><strong>Look for Circular Brands:</strong> Support businesses that take back old products for sorting and fiber-to-fiber recycling.</li>
          </ul>
        </div>
      )
    },
    {
      id: 'dietary-choices',
      title: 'Fork in the Road: How Dietary Choices Shape Our Climate Outlook',
      tag: 'Food & Diet',
      readTime: '8 min read',
      date: 'May 12, 2026',
      summary: 'From methane emissions to land use, discover why shifting our eating habits holds the highest individual leverage for saving CO2.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7eGblkkJTkXXdcTcd63Y6ActtaFNyBgFMBZq2GWB2Ar5Lg0jzdx8sl62n5M2RXelUaR5gU5c4JAbd3Ro75Sld1erBEOl4JUQsbaHJeEFSsvsG5HPy288CFnr91rmq9pnG7YuP3YmKdpz2ulL3bfRnGPz4MYur52PfWy9kXoFalosotqOjMFcsPlwojy7jstllYVXn398_klfgOKyKBst1StnWQSj-Ex3SzgWCai4LyQckLNDRlOaEI8AvJFAKwaeMTgpvYr60bqdm',
      content: (
        <div className="blog-modal-text">
          <p>Food accounts for roughly 26% of global greenhouse gas emissions. The agricultural system uses huge tracts of land and water resources, making our daily diets a major driver of ecological degradation.</p>
          <h3>The Methane Connection & Land Demands</h3>
          <p>Ruminant livestock (such as beef, sheep, and dairy cows) produce methane (CH₄) through enteric fermentation. Methane is a greenhouse gas that is up to 80 times more potent at trapping heat than carbon dioxide over a 20-year period.</p>
          <p>Additionally, forest land is continually cleared to grow feed crops (like soy) or build cattle pastures. This deforestation releases carbon stored in old soils and removes carbon-absorbing canopies. To put this in perspective, producing one kilogram of beef releases around 60-99 kg of CO₂ equivalents, whereas producing a kilogram of peas releases less than 1 kg.</p>
          <h3>Structuring a Pragmatic Food Transition</h3>
          <p>You don't need to go vegan overnight to make an impact. Incremental, systemic changes are highly beneficial:</p>
          <ol>
            <li><strong>The Flexitarian Shift:</strong> Swapping red meat for poultry, fish, or legumes a few days a week can reduce your diet footprint by 30-40%.</li>
            <li><strong>Embracing Plant-Based Alternatives:</strong> Modern plant proteins and oat/soy milks release significantly fewer emissions and require minimal water compared to their dairy/livestock counterparts.</li>
            <li><strong>Eliminate Food Waste:</strong> Roughly one-third of all food produced is lost or thrown away. When food spoils in landfills, it decomposes anaerobically and releases pure methane. Planning meals, proper storage, and composting are critical.</li>
          </ol>
        </div>
      )
    },
    {
      id: 'sustainable-transit',
      title: 'Beyond the Commute: The Next Wave of Low-Carbon Urban Transit',
      tag: 'Transport',
      readTime: '7 min read',
      date: 'April 22, 2026',
      summary: 'Electrification, active travel networks, and grid capacity are shifting how we view our daily commute and travels.',
      image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuA7eGblkkJTkXXdcTcd63Y6ActtaFNyBgFMBZq2GWB2Ar5Lg0jzdx8sl62n5M2RXelUaR5gU5c4JAbd3Ro75Sld1erBEOl4JUQsbaHJeEFSsvsG5HPy288CFnr91rmq9pnG7YuP3YmKdpz2ulL3bfRnGPz4MYur52PfWy9kXoFalosotqOjMFcsPlwojy7jstllYVXn398_klfgOKyKBst1StnWQSj-Ex3SzgWCai4LyQckLNDRlOaEI8AvJFAKwaeMTgpvYr60bqdm',
      content: (
        <div className="blog-modal-text">
          <p>Transportation represents nearly 15-20% of global greenhouse emissions. As cities swell and travel demands grow, our reliance on fossil fuel combustion engines must transition to electric drivetrains and active pathways.</p>
          <h3>Electric Vehicles vs. Active Transit</h3>
          <p>While Electric Vehicles (EVs) eliminate tailpipe emissions, their manufacturing footprint is larger than combustion engine vehicles due to raw materials in batteries. EVs only reach full emission-reduction potential when charged from a grid dominated by renewable energy (solar, wind, hydro).</p>
          <p>Active transport (walking, bicycling, or riding electric scooters) remains the gold standard. Active transit creates zero operational emissions and promotes high-density, healthy community layouts.</p>
          <h3>The Heavy Toll of High-Altitude Flight</h3>
          <p>A single international flight can double an individual's entire annual carbon footprint. Jet engines burn massive amounts of kerosene fuel at high altitudes. Beyond CO₂, aviation creates water vapor contrails and nitrous oxides, which trap additional heat at high elevations, multiplying the greenhouse effect by up to 2-3x relative to surface combustion.</p>
          <h3>Practical Transit Resolutions</h3>
          <ul>
            <li><strong>Integrate Public Transit:</strong> Trains, subways, and bus networks share carbon overheads among hundreds of riders, lowering per-capita emissions by 75% or more.</li>
            <li><strong>Embrace Micro-Mobility:</strong> For trips under 5 kilometers, walk or ride an e-bike to bypass traffic congestion and fuel combustion entirely.</li>
            <li><strong>Fly Smart:</strong> Avoid short regional flights where train alternatives exist. When flying is necessary, select direct routes (takeoff and landing consume the most fuel) and pack light to reduce aircraft payload.</li>
          </ul>
        </div>
      )
    }
  ];

  // Smooth scroll handler
  const scrollToSection = useCallback((section: 'methodology' | 'blog' | 'offset') => {
    setActiveTab(section);
    let targetRef;
    if (section === 'methodology') targetRef = methodologyRef;
    if (section === 'blog') targetRef = blogRef;
    if (section === 'offset') targetRef = offsetRef;

    if (targetRef && targetRef.current) {
      targetRef.current.scrollIntoView({ behavior: 'smooth', block: 'start' });
    }
  }, []);

  // React to initial navigation section clicked in footer
  useEffect(() => {
    if (initialSection) {
      // Delay slightly to allow the view to mount fully
      const timer = setTimeout(() => {
        scrollToSection(initialSection);
        if (onClearSection) {
          onClearSection();
        }
      }, 100);
      return () => clearTimeout(timer);
    }
  }, [initialSection, onClearSection, scrollToSection]);

  // Scroll Spy using scroll listener
  useEffect(() => {
    const handleScroll = () => {
      const scrollPosition = window.scrollY;
      
      const getOffset = (ref: React.RefObject<HTMLDivElement>) => {
        if (!ref.current) return Infinity;
        return ref.current.offsetTop - 160;
      };

      const blogOffset = getOffset(blogRef);
      const offsetOffset = getOffset(offsetRef);

      if (scrollPosition < 50) {
        setActiveTab('methodology');
        return;
      }

      if (scrollPosition >= offsetOffset - 50) {
        setActiveTab('offset');
      } else if (scrollPosition >= blogOffset - 50) {
        setActiveTab('blog');
      } else {
        setActiveTab('methodology');
      }
    };

    window.addEventListener('scroll', handleScroll, { passive: true });
    // Run after a short delay to allow layouts to calculate offsetTop correctly
    const timer = setTimeout(handleScroll, 100);

    return () => {
      window.removeEventListener('scroll', handleScroll);
      clearTimeout(timer);
    };
  }, []);

  return (
    <div className="resources-page font-body-md">
      {/* Hero Header */}
      <div className="resources-hero">
        <h1 className="font-display font-bold">Climate Resources Hub</h1>
        <p className="font-body-md text-bark-gray">
          Empowering your carbon-neutral journey with scientific methodology, environmental blog insights, and high-quality offset guidance.
        </p>
      </div>

      {/* Sticky Tab Navigator */}
      <div className="resources-nav-tabs">
        <button 
          className={`resources-tab-btn ${activeTab === 'methodology' ? 'active' : ''}`}
          onClick={() => scrollToSection('methodology')}
        >
          <HelpCircle size={18} />
          Methodology
        </button>
        <button 
          className={`resources-tab-btn ${activeTab === 'blog' ? 'active' : ''}`}
          onClick={() => scrollToSection('blog')}
        >
          <BookOpen size={18} />
          Climate Blog
        </button>
        <button 
          className={`resources-tab-btn ${activeTab === 'offset' ? 'active' : ''}`}
          onClick={() => scrollToSection('offset')}
        >
          <Leaf size={18} />
          Offset Guide
        </button>
      </div>

      {/* METHODOLOGY SECTION */}
      <div ref={methodologyRef} id="methodology" className="resources-section">
        <div className="section-header">
          <div className="section-icon-wrap">
            <HelpCircle size={24} />
          </div>
          <h2 className="font-display">Carbon Calculation Methodology</h2>
        </div>

        <div className="methodology-summary-card">
          <h3 className="font-display font-bold">How CarbonTree Calculates Your Footprint</h3>
          <p>
            Our estimation calculator translates everyday consumer habits and home energy choices into kilograms of carbon dioxide equivalents (kg CO₂e) per year. We then contextualize this by calculating the equivalent trees cut—based on the scientific baseline that a mature, healthy tree absorbs approximately <strong>22 kg of CO₂ per year</strong>.
          </p>
        </div>

        <div className="methodology-grid">
          {/* Card 1: Home Energy */}
          <div className="methodology-card">
            <div className="methodology-card-header">
              <Home className="text-eco-green" size={24} />
              <h3 className="methodology-card-title">1. Residential Energy Calculations</h3>
            </div>
            <p className="methodology-card-desc">
              We baseline your home energy footprint using the base emissions from your housing type. We divide this base footprint by your household occupant multiplier, scale it based on your HVAC cooling/heating habits, and apply an 85% discount if you rely on solar power or green tariffs.
            </p>
            <div className="methodology-formula">
              Footprint = Base × OccupantMult × HVACMult × RenewableDiscount
            </div>
            <div className="methodology-multiplier-list">
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Apartment / Single / Detached / Villa</span>
                <span className="methodology-multiplier-val">1200 / 2200 / 4000 / 6500 kg</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Occupants (Alone / 2 / 3-4 / 5+)</span>
                <span className="methodology-multiplier-val">1.0x / 0.65x / 0.48x / 0.35x</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Green/Solar Energy Discount</span>
                <span className="methodology-multiplier-val">-85% (0.15x Multiplier)</span>
              </div>
            </div>
          </div>

          {/* Card 2: Transport */}
          <div className="methodology-card">
            <div className="methodology-card-header">
              <Car className="text-eco-green" size={24} />
              <h3 className="methodology-card-title">2. Commute & Flight Travels</h3>
            </div>
            <p className="methodology-card-desc">
              Your commute footprint combines local commute mode, weekly time in transit, and flight frequency. High-altitude flight values represent kerosene fuel burn multiplied by a radiative forcing index (RFI) of 2.0 to account for cloud contrail warmth.
            </p>
            <div className="methodology-formula">
              Footprint = (CommuteBase × HoursMultiplier) + FlightImpact
            </div>
            <div className="methodology-multiplier-list">
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Commute (Active / Public / EV / Petrol)</span>
                <span className="methodology-multiplier-val">0 / 420 / 750 / 3800 kg</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Commute Time (Occasional to Road Warrior)</span>
                <span className="methodology-multiplier-val">0.45x to 2.75x</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Flights (Occasional to Long-Haul)</span>
                <span className="methodology-multiplier-val">600 to 4800 kg</span>
              </div>
            </div>
          </div>

          {/* Card 3: Diet & Food */}
          <div className="methodology-card">
            <div className="methodology-card-header">
              <Utensils className="text-eco-green" size={24} />
              <h3 className="methodology-card-title">3. Dietary Emissions & Sourcing</h3>
            </div>
            <p className="methodology-card-desc">
              Dietary emissions account for agricultural land clearance, fertilizer nitrous oxide, and livestock methane. We start with your diet base and scale it based on packaging waste, grocery transport, and composting habits.
            </p>
            <div className="methodology-formula">
              Footprint = DietBase × FoodWasteMultiplier
            </div>
            <div className="methodology-multiplier-list">
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Diet (Vegan / Vegetarian / Meat-Lover)</span>
                <span className="methodology-multiplier-val">650 / 1250 / 2600 / 3900 kg</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Eco-conscious / High-Waste Multiplier</span>
                <span className="methodology-multiplier-val">0.75x to 1.35x</span>
              </div>
            </div>
          </div>

          {/* Card 4: Lifestyle & Waste */}
          <div className="methodology-card">
            <div className="methodology-card-header">
              <ShoppingBag className="text-eco-green" size={24} />
              <h3 className="methodology-card-title">4. Lifestyle & Material Goods</h3>
            </div>
            <p className="methodology-card-desc">
              Lifestyle calculations estimate industrial supply chain emissions for clothing, electronics, and standard retail goods. These emissions are offset (subtracted) by household sorting, organic compost, and paper/plastic recycling habits.
            </p>
            <div className="methodology-formula">
              Footprint = Max(100, ShoppingBase + RecyclingOffset)
            </div>
            <div className="methodology-multiplier-list">
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Consumer Type (Minimalist / High Spender)</span>
                <span className="methodology-multiplier-val">450 / 1400 / 3200 kg</span>
              </div>
              <div className="methodology-multiplier-item">
                <span className="methodology-multiplier-label">Recycling Offset (Selective / Everything)</span>
                <span className="methodology-multiplier-val">-100 kg / -350 kg</span>
              </div>
            </div>
          </div>
        </div>
      </div>

      {/* CLIMATE BLOG SECTION */}
      <div ref={blogRef} id="blog" className="resources-section">
        <div className="section-header">
          <div className="section-icon-wrap">
            <BookOpen size={24} />
          </div>
          <h2 className="font-display">Climate & Habits Blog</h2>
        </div>

        <div className="blog-grid">
          {articles.map((article) => (
            <div 
              key={article.id} 
              className="blog-card"
              onClick={() => setSelectedArticle(article)}
            >
              <div className="blog-card-img-wrap">
                <span className="blog-card-tag">{article.tag}</span>
                <img 
                  className="blog-card-img" 
                  src={article.image} 
                  alt={article.title} 
                />
              </div>
              <div className="blog-card-content">
                <div className="blog-card-meta font-label-sm">
                  <span className="flex items-center gap-1">
                    <Calendar size={12} />
                    {article.date}
                  </span>
                  <span className="flex items-center gap-1">
                    <Clock size={12} />
                    {article.readTime}
                  </span>
                </div>
                <h3 className="blog-card-title font-display font-bold">{article.title}</h3>
                <p className="blog-card-summary font-body-sm">{article.summary}</p>
                <div className="blog-card-footer font-label-md">
                  Read Article
                  <ArrowRight size={14} />
                </div>
              </div>
            </div>
          ))}
        </div>
      </div>

      {/* CARBON OFFSET GUIDE SECTION */}
      <div ref={offsetRef} id="offset" className="resources-section">
        <div className="section-header">
          <div className="section-icon-wrap">
            <Leaf size={24} />
          </div>
          <h2 className="font-display">Carbon Offset Guide</h2>
        </div>

        <p className="offset-intro">
          Carbon offsetting allows individuals and organizations to compensate for unavoidable carbon emissions by supporting environmental projects that absorb, capture, or prevent greenhouse gases from reaching the atmosphere. Used properly, offsets are a key stepping stone on the road to net-zero.
        </p>

        {/* Recommended Project Programs */}
        <h3 className="offset-projects-title font-display font-bold">Recommended Offset Solutions</h3>
        <div className="offset-projects-grid">
          {/* Project 1 */}
          <div className="offset-project-card">
            <div className="offset-proj-header">
              <Trees className="offset-proj-icon" size={24} />
              <span className="offset-proj-badge">Medium Term</span>
            </div>
            <h4 className="font-display font-bold">Reforestation</h4>
            <p className="font-body-sm">
              Planting native, diverse tree species on degraded grazing lands. Absorbs carbon organically as forests grow, supporting regional wildlife.
            </p>
            <div className="offset-project-efficiency">
              Permanence: <span>30 - 100 years</span>
            </div>
          </div>

          {/* Project 2 */}
          <div className="offset-project-card">
            <div className="offset-proj-header">
              <Anchor className="offset-proj-icon" size={24} />
              <span className="offset-proj-badge">High Absorption</span>
            </div>
            <h4 className="font-display font-bold">Blue Carbon Sinks</h4>
            <p className="font-body-sm">
              Restoring coastal seagrass and mangrove habitats. Ocean wetlands absorb carbon up to 10 times faster than tropical land forests.
            </p>
            <div className="offset-project-efficiency">
              Permanence: <span>50 - 100+ years</span>
            </div>
          </div>

          {/* Project 3 */}
          <div className="offset-project-card">
            <div className="offset-proj-header">
              <Flame className="offset-proj-icon" size={24} />
              <span className="offset-proj-badge">High Permanence</span>
            </div>
            <h4 className="font-display font-bold">Biochar & Pyrolysis</h4>
            <p className="font-body-sm">
              Heating crop waste in an oxygen-free chamber, turning organic matter into pure carbon charcoal. Mixed with topsoils to retain nutrients.
            </p>
            <div className="offset-project-efficiency">
              Permanence: <span>500+ years</span>
            </div>
          </div>

          {/* Project 4 */}
          <div className="offset-project-card">
            <div className="offset-proj-header">
              <ShieldCheck className="offset-proj-icon" size={24} />
              <span className="offset-proj-badge">Social Benefit</span>
            </div>
            <h4 className="font-display font-bold">Clean Cookstoves</h4>
            <p className="font-body-sm">
              Replacing open wood fires in developing regions with clean fuel stoves. Cuts fuel needs by half, preventing deforestation and saving lives.
            </p>
            <div className="offset-project-efficiency">
              Permanence: <span>10 - 20 years</span>
            </div>
          </div>
        </div>
      </div>

      {/* ARTICLE READER MODAL */}
      {selectedArticle && (
        <div className="blog-modal-overlay" onClick={() => setSelectedArticle(null)}>
          <div className="blog-modal-content" onClick={(e) => e.stopPropagation()}>
            <button 
              className="blog-modal-close" 
              onClick={() => setSelectedArticle(null)}
              aria-label="Close Article"
            >
              <X size={20} />
            </button>
            <div className="blog-modal-hero">
              <img src={selectedArticle.image} alt={selectedArticle.title} />
            </div>
            <div className="blog-modal-body">
              <div className="blog-modal-meta font-label-sm">
                <span className="flex items-center gap-1">
                  <Calendar size={14} />
                  {selectedArticle.date}
                </span>
                <span className="flex items-center gap-1">
                  <Clock size={14} />
                  {selectedArticle.readTime}
                </span>
                <span className="offset-proj-badge">{selectedArticle.tag}</span>
              </div>
              <h2 className="blog-modal-title font-display font-bold">{selectedArticle.title}</h2>
              {selectedArticle.content}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};
